parameters:
    pimcore_legacy.cache.config.zend.prefix: 'zf_'
    pimcore_legacy.cache.config.zend.default_lifetime: '%pimcore.cache.core.default_lifetime%'

    # default frontend options including a specific ZF prefix
    pimcore_legacy.cache.zend.frontend.options:
        cache_id_prefix: '%pimcore_legacy.cache.config.zend.prefix%'
        lifetime: '%pimcore_legacy.cache.config.zend.default_lifetime%'
        automatic_serialization: true
        automatic_cleaning_factor: 0

services:
    # the PimcoreCacheItemPool backend delegates caching to the core cache adapter
    pimcore_legacy.cache.zend.backend:
        class: Pimcore\Cache\Backend\PimcoreCacheItemPool
        arguments: ['@pimcore.cache.core.pool']

    # this frontend will be injected into ZF classes if defined
    pimcore_legacy.cache.zend.frontend:
        class: Zend_Cache_Core
        arguments: ['%pimcore_legacy.cache.zend.frontend.options%']
        calls:
            - [setBackend, ['@pimcore_legacy.cache.zend.backend']]

    # the cache handler acts as cache interface to Pimcore\Cache
    pimcore_legacy.cache.zend.handler:
        class: Pimcore\Cache\Core\ZendCacheHandler
        arguments: ['@pimcore_legacy.cache.zend.frontend']



