services:
    pimcore.legacy_kernel:
        class: PimcoreLegacyBundle\HttpKernel\Kernel
        arguments: ['@kernel']

    pimcore.legacy.fallback_router:
        class: PimcoreLegacyBundle\Routing\FallbackRouter
        arguments: ['@router.request_context']
        tags:
            - { name: router, priority: -200 }

    # executes ZF1 view helpers
    pimcore.legacy.zend_view_helper_bridge:
        class: PimcoreLegacyBundle\Zend\View\ViewHelperBridge
        arguments: ['@pimcore.legacy.zend_view_provider', '@pimcore.service.request.template_vars_resolver']

    # creates configured Pimcore\View instances
    pimcore.legacy.zend_view_provider:
        class: PimcoreLegacyBundle\Zend\View\ViewProvider

    # legacy tag handler supporting Pimcore\View - injected into delegating tag handler in compiler pass
    pimcore.document.tag.handler.legacy:
        class: PimcoreLegacyBundle\Document\Tag\LegacyTagHandler

    # provides rendering of documents with legacy ZF1 stack
    pimcore.templating.legacy_document_renderer:
      class: PimcoreLegacyBundle\Templating\Renderer\DocumentRenderer
      arguments: ['@pimcore.legacy_kernel']

    # adds legacy plugin assets to admin interface and editmode
    pimcore.legacy.plugin_asset_listener:
        class: PimcoreLegacyBundle\EventListener\PluginAssetListener
        tags:
            - { name: kernel.event_subscriber }
