services:
    _defaults:
        autowire: true
        autoconfigure: true

    # aliases for BC
    pimcore.legacy_kernel: '@Pimcore\Bundle\LegacyBundle\HttpKernel\Kernel'
    pimcore.legacy.fallback_router: '@Pimcore\Bundle\LegacyBundle\Routing\FallbackRouter'
    pimcore.legacy.plugin_broker: '@Pimcore\API\Plugin\Broker'
    pimcore.legacy.controller.admin.extension_manager: '@Pimcore\Bundle\LegacyBundle\Controller\Admin\ExtensionManager\LegacyExtensionManagerController'
    pimcore.legacy.zend_view_helper_bridge: '@Pimcore\Bundle\LegacyBundle\Zend\View\ViewHelperBridge'
    pimcore.legacy.zend_view_provider: '@Pimcore\Bundle\LegacyBundle\Zend\View\ViewProvider'
    pimcore.document.tag.handler.legacy: '@Pimcore\Bundle\LegacyBundle\Document\Tag\LegacyTagHandler'
    pimcore.legacy.document.renderer: '@Pimcore\Bundle\LegacyBundle\Document\Renderer\LegacyDocumentRenderer'
    pimcore.legacy.templating.view_helper.pimcore_url: '@Pimcore\Bundle\LegacyBundle\Templating\Helper\PimcoreUrl'

    Pimcore\Bundle\LegacyBundle\HttpKernel\Kernel:
        arguments:
            - '@kernel'

    Pimcore\Bundle\LegacyBundle\Routing\FallbackRouter:
        arguments:
            - '@router.request_context'
        tags:
            - { name: router, priority: -200 }

    Pimcore\API\Plugin\Broker: ~

    # the legacy extension manager controller is defined as service as it is used
    # by the extension manager controller to get the list of legacy extensions
    Pimcore\Bundle\LegacyBundle\Controller\Admin\ExtensionManager\LegacyExtensionManagerController:
        calls:
            - [setContainer, ['@service_container']]

    # executes ZF1 view helpers
    Pimcore\Bundle\LegacyBundle\Zend\View\ViewHelperBridge: ~

    # creates configured Pimcore\View instances
    Pimcore\Bundle\LegacyBundle\Zend\View\ViewProvider: ~

    # legacy tag handler supporting Pimcore\View - injected into delegating tag handler in compiler pass
    Pimcore\Bundle\LegacyBundle\Document\Tag\LegacyTagHandler: ~

    # provides rendering of documents with legacy ZF1 stack
    Pimcore\Bundle\LegacyBundle\Document\Renderer\LegacyDocumentRenderer: ~

    # decorates default pimcore_url helper and adds fallback to legacy static routes
    Pimcore\Bundle\LegacyBundle\Templating\Helper\PimcoreUrl:
        decorates: Pimcore\Templating\Helper\PimcoreUrl
        arguments:
             $generator: '@router'
