services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # injects ZF1 view helpers into templating
    Pimcore\Bundle\LegacyBundle\Templating\HelperBroker\ZendViewHelper:
        tags:
            - { name: pimcore.templating.helper_broker, priority: -10 }
